version: '3.5'

services:
  laravel_zero:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        - USER_ID
        - GROUP_ID
    container_name: app_zero
    volumes:
      - ./src:/var/www
    environment:
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT}
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    depends_on:
      - mysql
      #- redis

  mysql:
    platform: linux/amd64
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    container_name: mysql_zero_db
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: laravel_db
    ports:
      - "3506:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6380:6379"
#      - "6380:6379/udp"
#    environment:
#      REDIS_PASSWORD: redisroot
#    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redisroot"]